# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# Сгенерированный файл с главным окном по составленному ранее интерфейсу в QT Designer
# Чтобы сгенерировать данный файл, необходимо воспользоваться командой:
# pyuic6 chat.ui -o client_chat.py ,
# где chat.ui - имя сохранённого файла из QT Designer,
# client_chat.py - имя для файла, который необходимо сгенерировать
# ВНИМАНИЕ: не следует писать сюда вручную какой-либо код, так как при следующем его обновлении всё сотрется
# имейте это ввиду

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 517)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nickname = QtWidgets.QLineEdit(self.centralwidget)
        self.nickname.setEnabled(True)
        self.nickname.setGeometry(QtCore.QRect(245, 15, 281, 31))
        self.nickname.setObjectName("nickname")
        self.ok = QtWidgets.QPushButton(self.centralwidget)
        self.ok.setGeometry(QtCore.QRect(530, 12, 61, 41))
        self.ok.setObjectName("ok")
        self.messages = QtWidgets.QTextBrowser(self.centralwidget)
        self.messages.setGeometry(QtCore.QRect(20, 60, 571, 361))
        self.messages.setObjectName("messages")
        self.msg_line = QtWidgets.QLineEdit(self.centralwidget)
        self.msg_line.setEnabled(False)
        self.msg_line.setGeometry(QtCore.QRect(20, 436, 471, 41))
        self.msg_line.setObjectName("msg_line")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setEnabled(False)
        self.send.setGeometry(QtCore.QRect(496, 433, 101, 51))
        self.send.setObjectName("send")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Choose your nickname:"))
        self.ok.setText(_translate("MainWindow", "OK"))
        self.send.setText(_translate("MainWindow", "Send"))

# comPyQter
